services:
  database:
    image: postgres:18-alpine
    container_name: finch-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: finch
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finch_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: